language: php

php:
  - 7.3
  - 7.4

script:
  - mkdir -p build/logs

  - composer outdated -D --strict

  - composer require squizlabs/php_codesniffer --dev
  - vendor/bin/phpcs src --standard=PSR2 -n
  - composer remove squizlabs/php_codesniffer --dev

  - composer require phpstan/phpstan --dev
  - vendor/bin/phpstan analyze src --level max --no-progress
  - composer remove phpstan/phpstan --dev

  - composer require efabrica/php-extensions-finder --dev
  - vendor/bin/php-extensions-finder check src tests
  - composer remove efabrica/php-extensions-finder --dev

  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
